/** Represents the lifecycle status of a single SQL query. */
export type QueryStatus = "pending" | "executing" | "completed" | "error";

/**
 * Supported chart/visualization types for displaying query results.
 * "table" is the default fallback.
 */
export type ChartType = "table" | "bar" | "line" | "pie" | "area";

/** Pagination metadata returned by the query execution API. */
export interface PaginationInfo {
  page: number;
  pageSize: number;
  totalRows: number;
  totalPages: number;
}

/** Represents a single SQL query generated by the AI, along with its execution result. */
export interface QueryResult {
  /** Human-readable title describing what this query retrieves. */
  title: string;
  /** The raw SQL string generated by the AI. */
  sql: string;
  /** Column names for the result set. */
  columns: string[];
  /** Preferred chart type for visualizing this result. */
  chartType: ChartType;
  /** Rows returned by the query execution. Undefined until executed. */
  rows?: Record<string, unknown>[];
  /** Error message from query execution, or null if successful. */
  queryError: string | null;
  /** Pre-execution validation error (e.g. blocked SQL). */
  validationError?: string;
  /** Time taken to execute the query in milliseconds. */
  executionTimeMs?: number;
  /** Current lifecycle status of this query. */
  status?: QueryStatus;
  /** Pagination info returned after execution. */
  pagination?: PaginationInfo;
}

/** The full AI response for a single user prompt. */
export interface AIResponse {
  /** Natural language explanation of the generated queries. */
  explanation: string;
  /** Streamed analytical insight generated after query execution. Null until available. */
  insight: string | null;
  /** List of SQL queries generated by the AI. */
  queries: QueryResult[];
}

/** A single message exchanged with the LLM. */
export interface Message {
  role: "user" | "assistant" | "system";
  content: string;
}

/** A single turn within a multi-turn conversation session. */
export interface ConversationTurn {
  id: string;
  role: "user" | "assistant";
  content: string;
  /** SQL queries associated with this turn (assistant only). */
  sql?: string[];
  /** Short summary of query results for conversation context injection. */
  resultSummary?: string;
  timestamp: number;
}

/** A conversation session containing multiple turns. */
export interface Conversation {
  id: string;
  title: string;
  turns: ConversationTurn[];
  createdAt: number;
  updatedAt: number;
}
